# Generated by Django 4.1.5 on 2023-01-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
