# Generated by Django 4.1.5 on 2023-01-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMSUsers', '0002_events_alter_registereduser_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
