# Generated by Django 4.1.5 on 2023-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSUsers', '0004_remove_event_id_event_eventno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
