# Generated by Django 4.1.5 on 2023-01-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSUsers', '0006_eventusermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventusermapping',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventusermapping',
            name='token',
            field=models.CharField(default='ds42as54', max_length=8, unique=True),
        ),
    ]
